services:
  mongodb:
    image: mongo:7.0
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  migrateur:
    build: .
    container_name: migrateur-container
    depends_on:
      - mongodb
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
      python scr/migration.py &&
      echo 'Migration OK' &&
      pytest tests/test_integrite.py &&
      echo 'Tests OK'
      "

volumes:
  mongo-data: